### ISSUE TITLE
Autheme 5.2 SnapShot

### ISSUE THREAD

**Issue by swan201** [ProtocolSupport/ProtocolSupportPremiumLogin#1]
Authme Devteam still version up and Change API. Bukkitdev File is too old. Can You remake to Authme 5.2 API?

**Comment by Shevchik** [comment]
According to what i see on github the NewAPI is still there, even the old one is, so there is no need for the update

**Comment by swan201** [comment]
@Shevchik But I can't use this plugins. Authme 5.2 Snapshot and This plugins using. I type /licence. Then Plugins have Internal Error.

Did i Something Wrong to use??

**Comment by Shevchik** [comment]
Maybe its the plugin load order. Should probably add softdepend

**Comment by Shevchik** [comment]
Try now

**Comment by swan201** [comment]
http://pastebin.com/DgZXvMTn

Still Plugins Send to me Error

**Comment by Shevchik** [comment]
Oh shi... Forgot about that.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by swan201** [comment]
@Shevchik Ok know fixed it. But I think This plugins is different my think. Can you explain about this plugins?

**Comment by Shevchik** [comment]
Didn't understand what you are saying.

**Comment by swan201** [comment]
@Shevchik ummm... I think This plugins is similar AutoIn Plugins. Premium member can bypass login plugins. but is wrong. enable Licence mode. Still Premium member need to login. So I want to explain this plugins :).

plz tell me about this plugins

**Comment by Shevchik** [comment]
Shouldn't be like that, probably an error somewhere in the code
